In [1]:
#Importing liabraries
import pandas as pd
import numpy as nd

In [2]:
print("Date: 2024-12-26")
print("Student ID: 500681622")
print("Purpose: Python Assignment")

Date: 2024-12-26
Student ID: 500681622
Purpose: Python Assignment


# TASK_1

In [3]:
#Importing dataset
data= pd.read_csv("D:/University/Semester1/Coding/Python project/bank-additional-full.csv")
print(data)

      age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"
0      56;"housemaid";"married";"basic.4y";"no";"no";...                                                                                                                                                                          
1      57;"services";"married";"high.school";"unknown...                                                                                                                                                                          
2      37;"services";"married";"high.school";"no";"ye...                                                                                                                                                                          
3      40;"admin.";"married";"basic.6y";"no";"no";"no...                                    

In [4]:
print("data preview:")
print(data.head())

data preview:
  age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"
0  56;"housemaid";"married";"basic.4y";"no";"no";...                                                                                                                                                                          
1  57;"services";"married";"high.school";"unknown...                                                                                                                                                                          
2  37;"services";"married";"high.school";"no";"ye...                                                                                                                                                                          
3  40;"admin.";"married";"basic.6y";"no";"no";"no...                                          

In [5]:
# Data_Manipulation
data= pd.read_csv("D:/University/Semester1/Coding/Python project/bank-additional-full.csv", delimiter=";", quotechar='"')
print(data.head())

   age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed

In [6]:
## Data_sampling
random_seed = 42
sampled_data = data.sample(frac=0.2, random_state=random_seed)
print("Sampled data preview:")
print(sampled_data.head())

Sampled data preview:
       age          job  marital    education  default housing loan  \
32884   57   technician  married  high.school       no      no  yes   
3169    55      unknown  married      unknown  unknown     yes   no   
32206   33  blue-collar  married     basic.9y       no      no   no   
9403    36       admin.  married  high.school       no      no   no   
14020   27    housemaid  married  high.school       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
32884   cellular   may         mon  ...         1    999         1   
3169   telephone   may         thu  ...         2    999         0   
32206   cellular   may         fri  ...         1    999         1   
9403   telephone   jun         fri  ...         4    999         0   
14020   cellular   jul         fri  ...         2    999         0   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
32884      failure         -1.8          92.893      

# TASK_2

# Job Backgrounds and Education Levels Analysis

In [7]:
# Assuming 'job' and 'education' are relevant features for analysis
X1 = sampled_data[['job', 'education']]
y1 = sampled_data['y']

# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)

# One-hot encoding for categorical variables
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define the transformer for one-hot encoding
preprocessor1 = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), ['job', 'education'])
    ],
    remainder='passthrough'
)

# Assuming Logistic Regression as the chosen classification algorithm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create a pipeline with one-hot encoding and logistic regression
model1 = Pipeline(steps=[
    ('preprocessor', preprocessor1),
    ('classifier', LogisticRegression(random_state=42))
])

# Training the model
model1.fit(X1_train, y1_train)

# Predicting responses on the test set
predictions1 = model1.predict(X1_test)

# Evaluating the model
accuracy1 = accuracy_score(y1_test, predictions1)
conf_matrix1 = confusion_matrix(y1_test, predictions1)
classification_report1 = classification_report(y1_test, predictions1)

# Displaying results
print(f"Accuracy: {accuracy1}")
print("\nConfusion Matrix:\n", conf_matrix1)
print("\nClassification Report:\n", classification_report1)

Accuracy: 0.8743932038834952

Confusion Matrix:
 [[1441    0]
 [ 207    0]]

Classification Report:
               precision    recall  f1-score   support

          no       0.87      1.00      0.93      1441
         yes       0.00      0.00      0.00       207

    accuracy                           0.87      1648
   macro avg       0.44      0.50      0.47      1648
weighted avg       0.76      0.87      0.82      1648



C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Contact Communication Type Analysis

In [8]:
# Assuming 'contact' is a relevant feature for analysis
X2 = sampled_data[['contact']]
y2 = sampled_data['y']

# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.2, random_state=42)

# One-hot encoding for the 'contact' column
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define the transformer for one-hot encoding
preprocessor2 = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), ['contact'])
    ],
    remainder='passthrough'
)

# Assuming Logistic Regression as the chosen classification algorithm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create a pipeline with one-hot encoding and logistic regression
model2 = Pipeline(steps=[
    ('preprocessor', preprocessor2),
    ('classifier', LogisticRegression(random_state=42))
])

# Training the model
model2.fit(X2_train, y2_train)

# Predicting responses on the test set
predictions2 = model2.predict(X2_test)

# Evaluating the model
accuracy2 = accuracy_score(y2_test, predictions2)
conf_matrix2 = confusion_matrix(y2_test, predictions2)
classification_report2 = classification_report(y2_test, predictions2)

# Displaying results
print(f"Accuracy: {accuracy2}")
print("\nConfusion Matrix:\n", conf_matrix2)
print("\nClassification Report:\n", classification_report2)

Accuracy: 0.8743932038834952

Confusion Matrix:
 [[1441    0]
 [ 207    0]]

Classification Report:
               precision    recall  f1-score   support

          no       0.87      1.00      0.93      1441
         yes       0.00      0.00      0.00       207

    accuracy                           0.87      1648
   macro avg       0.44      0.50      0.47      1648
weighted avg       0.76      0.87      0.82      1648



C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Age Groups Investigation

In [9]:
# Assuming 'age' and 'contact' are relevant features for analysis
X3 = sampled_data[['age', 'contact']]
y3 = sampled_data['y']

# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split

X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.2, random_state=42)

# One-hot encoding for the 'contact' column
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define the transformer for one-hot encoding
preprocessor3 = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), ['contact'])
    ],
    remainder='passthrough'
)

# Assuming Logistic Regression as the chosen classification algorithm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create a pipeline with one-hot encoding and logistic regression
model3 = Pipeline(steps=[
    ('preprocessor', preprocessor3),
    ('classifier', LogisticRegression(random_state=42))
])

# Training the model
model3.fit(X3_train, y3_train)

# Predicting responses on the test set
predictions3 = model3.predict(X3_test)

# Evaluating the model
accuracy3 = accuracy_score(y3_test, predictions3)
conf_matrix3 = confusion_matrix(y3_test, predictions3)
classification_report3 = classification_report(y3_test, predictions3)

# Displaying results
print(f"Accuracy: {accuracy3}")
print("\nConfusion Matrix:\n", conf_matrix3)
print("\nClassification Report:\n", classification_report3)

C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.8743932038834952

Confusion Matrix:
 [[1441    0]
 [ 207    0]]

Classification Report:
               precision    recall  f1-score   support

          no       0.87      1.00      0.93      1441
         yes       0.00      0.00      0.00       207

    accuracy                           0.87      1648
   macro avg       0.44      0.50      0.47      1648
weighted avg       0.76      0.87      0.82      1648



C:\ANA\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
#Relationship between education and responses
education_insight = sampled_data.groupby(['education', 'y']).size().unstack(fill_value=0)
print("\nInsight 1: Relationship between education and responses")
print(education_insight)

#Impact of campaign duration on responses
sampled_data['duration_category'] = pd.cut(sampled_data['duration'], bins=[0, 100, 200, 300, 400, 500, float('inf')], labels=['0-100', '101-200', '201-300', '301-400', '401-500', '501+'])
duration_insight = sampled_data.groupby(['duration_category', 'y']).size().unstack(fill_value=0)
print("\nInsight 2: Impact of campaign duration on responses")
print(duration_insight)


Insight 1: Relationship between education and responses
y                      no  yes
education                     
basic.4y              755   83
basic.6y              401   39
basic.9y             1144   93
high.school          1684  217
illiterate              4    1
professional.course   943  124
university.degree    2100  318
unknown               272   60

Insight 2: Impact of campaign duration on responses
y                    no  yes
duration_category           
0-100              1995   11
101-200            2388  128
201-300            1277  155
301-400             696  116
401-500             366   88
501+                581  437
